# Generated by Django 4.0.dev20210612144642 on 2021-08-28 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0003_student_subject_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='school',
            field=models.CharField(max_length=200),
        ),
    ]
