# Generated by Django 4.0.dev20210612144642 on 2021-08-28 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0005_alter_professor_school'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
