# Generated by Django 4.0.dev20210612144642 on 2021-08-28 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0006_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=400)),
                ('professor_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_api.professor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_api.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_api.subject')),
            ],
        ),
    ]
