# Generated by Django 4.0.dev20210612144642 on 2021-08-28 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(default='', max_length=100),
        ),
    ]
