# Generated by Django 4.0.dev20210612144642 on 2021-08-28 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0008_subject_subject_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
