# Generated by Django 4.0.dev20210612144642 on 2021-08-29 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0010_subject_professor_subject_review_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='student',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
